NumPy:
-----------
- NumPy is a python library used for numerical data like working with arrays.
- it consists of Scientific data calculations, Linear algebra, matrices etc

In [1]:
! pip install numpy  # for installation
import numpy as np  # importing the library

In [3]:
## 1-d array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
a.dtype

dtype('int32')

In [5]:
b = np.array([1,23,45,"gh"])
print(b)

['1' '23' '45' 'gh']


In [6]:
b.dtype

dtype('<U11')

In [7]:
k1 = [1,"234",89.23,"string"]
c = np.array(k1)
print(c)

['1' '234' '89.23' 'string']


In [9]:
r = np.arange(1,10,2)
r

array([1, 3, 5, 7, 9])

In [10]:
r.nbytes ## checking the memory space occupied by array

20

In [11]:
r.itemsize # each element size

4

ndarray Properties:
-------------------------------
- ndim
    - returns no of dimensions of an array
- shape
    - returns the no of rows and columns
- size
    - returns the size of an array
- dtype
    - we can specify the dtype like numpy.int32, numpy.int16 and numpy.float64
    - we can know the existing dtype
- itemsize
    - returns the size in bytes of each element in an array

In [12]:
a

array([1, 2, 3, 4, 5])

In [13]:
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.itemsize)
print(a.size)

1
(5,)
int32
4
5


In [15]:
a = np.append(a,[13,27,29])
a

array([ 1,  2,  3,  4,  5, 13, 27, 29])

In [16]:
ln = np.linspace(1,10,10) # creating an array with in the given range with required number of elements
ln

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
ln1 = np.linspace(1,3,10)

In [18]:
ln1

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [21]:
lg = np.logspace(1,10,20)

In [22]:
lg

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [23]:
np.full(10,"abc") # repeating required no of times with given value

array(['abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc',
       'abc'], dtype='<U3')

In [25]:
np.zeros(10,dtype=int) # fills an array with 0s by requires no of times

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [27]:
## 2d array 
a2 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(a2.ndim)
print(a2.dtype)
print(a2.itemsize,a2.size,a2.shape)

2
int32
4 9 (3, 3)


In [29]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
a3 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
    ])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [33]:
ma = np.array([1,2,3,4,5,6,7,8,9,10,11,12],ndmin=3)
ma

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]])

In [34]:
a

array([ 1,  2,  3,  4,  5, 13, 27, 29])

In [35]:
a[0]

1

In [36]:
a[-1]

29

In [37]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a2[2][1]

8

In [44]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
a3[0][1][0]

4

In [49]:
a3[1][0][2]

9

In [54]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
a2[[0,1,0],[1,2,0]] # a[(0,1),(1,2),(0,0)]

array([2, 6, 1])

In [57]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
a3[[1,0,1],[0,1,1],[2,1,0]] # [(1,0,2),(0,1,1),(1,1,0)]

array([ 9,  5, 10])

In [63]:
a3[(1,0,2)]

9

In [66]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
a3[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
a3[2][0][1]